title: R Sandboxes

polleverywhere:
  url: https://www.pollev.com/

askforme:
  url: https://docs.google.com/forms/
  use_custom_form: false
  form_id:
  text_input_name:

padlet:
  url: https://padlet.com/

sandbox:
  class:
    lang: r
    height: 350
    show-run-button: true
    show-solution-before: false
    no-lazy-load: true
    pre-exercise-code: |
      require(readr)
      require(mosaic)
      require(supernova)
      require(lsr)
    sample-code: null
    solution: null
    sct: null
    hint: null
  quiz:
    lang: r
    height: 350
    show-run-button: true
    show-solution-before: false
    no-lazy-load: true
    pre-exercise-code: |
      require(readr)
      require(mosaic)
      require(supernova)
      require(lsr)
    sample-code: null
    solution: null
    sct: null
    hint: null
